/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "var(--nest-surface)",
        "surface-dim": "var(--nest-surface-dim)",
        "surface-bright": "var(--nest-surface-bright)",
        "surface-container-lowest": "var(--nest-surface-container-lowest)",
        "surface-container-low": "var(--nest-surface-container-low)",
        "surface-container": "var(--nest-surface-container)",
        "surface-container-high": "var(--nest-surface-container-high)",
        "surface-container-highest": "var(--nest-surface-container-highest)",
        "on-surface": "var(--nest-on-surface)",
        "on-surface-variant": "var(--nest-on-surface-variant)",
        "inverse-surface": "var(--nest-inverse-surface)",
        "inverse-on-surface": "var(--nest-inverse-on-surface)",
        "outline": "var(--nest-outline)",
        "outline-variant": "var(--nest-outline-variant)",
        "primary": "var(--nest-primary)",
        "primary-container": "var(--nest-primary-container)",
        "on-primary": "var(--nest-on-primary)",
        "on-primary-container": "var(--nest-on-primary-container)",
        "primary-fixed": "var(--nest-primary-fixed)",
        "primary-fixed-dim": "var(--nest-primary-fixed-dim)",
        "secondary": "var(--nest-secondary)",
        "on-secondary": "var(--nest-on-secondary)",
        "secondary-container": "var(--nest-secondary-container)",
        "tertiary": "var(--nest-tertiary)",
        "tertiary-container": "var(--nest-tertiary-container)",
        "error": "var(--nest-error)",
        "error-container": "var(--nest-error-container)",
        "on-error": "var(--nest-on-error)",
        "on-error-container": "var(--nest-on-error-container)",
        "background": "var(--nest-background)",
        "on-background": "var(--nest-on-background)",
        "surface-variant": "var(--nest-surface-variant)",
      },
      fontFamily: {
        display: ["'Plus Jakarta Sans'", "system-ui", "-apple-system", "BlinkMacSystemFont", "'Segoe UI'", "Roboto", "Helvetica", "Arial", "sans-serif"],
        headline: ["'Plus Jakarta Sans'", "system-ui", "-apple-system", "BlinkMacSystemFont", "'Segoe UI'", "Roboto", "Helvetica", "Arial", "sans-serif"],
        body: ["'Inter'", "system-ui", "-apple-system", "BlinkMacSystemFont", "'Segoe UI'", "Roboto", "Helvetica", "Arial", "sans-serif"],
        caption: ["'Inter'", "system-ui", "-apple-system", "BlinkMacSystemFont", "'Segoe UI'", "Roboto", "Helvetica", "Arial", "sans-serif"],
        mono: ["ui-monospace", "SFMono-Regular", "Menlo", "Monaco", "Consolas", "monospace"],
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
        "space-2xl": "4rem",
        "space-3xl": "6rem",
        "gutter": "1.5rem",
        "gutter-mobile": "1rem",
        "margin": "3rem",
        "margin-tablet": "2rem",
        "margin-mobile": "1.25rem",
      },
      borderRadius: {
        "sm": "0.25rem",
        "DEFAULT": "0.375rem",
        "md": "0.5rem",
        "lg": "0.75rem",
        "xl": "1rem",
        "2xl": "1.5rem",
        "full": "9999px",
      },
      boxShadow: {
        "card": "0 1px 3px rgba(0,0,0,0.03), 0 1px 2px rgba(0,0,0,0.02)",
        "popover": "0 8px 24px -4px rgba(18, 19, 22, 0.08)",
        "modal": "0 20px 48px -8px rgba(18, 19, 22, 0.2)",
      }
    },
  },
  plugins: [],
}
